package objects;

import java.util.EnumMap;

/**
 * Driver's license. Proved by a File.
 */
public class License extends DataObject {

    public enum Field implements DataField {

	ID(Integer.class, true, false),
	NUMBER(String.class), 
	FILE(Integer.class);

	private final boolean stamp;
	private final boolean key;
	private final Class type;

	private Field(Class type, boolean key, boolean stamp) {
		this.type = type;
		this.key = key;
		this.stamp = stamp;
	}
	
	private Field(Class type) {
		this.type = type;
		this.key = false;
		this.stamp = false;
	}
	
	@Override
	public Class getType() {
		return type;
	}

	@Override
	public boolean isKey() {
		return key;
	}

	@Override
	public boolean isStamp() {
		return stamp;
	}

    }
    
    

    /**
     *
     * @param id generated by db
     * @param number license number
     * @param file File as proof of license
     */
    public License(Integer id, String number, Integer file) {
        super(new EnumMap<>(Field.class));
        data.put(Field.ID, id);
        data.put(Field.NUMBER, number);
        data.put(Field.FILE, file);
    }

    /**
     *
     * @return the id assigned by the db
     */
    public Integer getId() {
        return (Integer) data.get(Field.ID);
    }

    /**
     *
     * @return the license number
     */
    public String getNumber() {
        return (String) data.get(Field.NUMBER);
    }

    /**
     *
     * @param number the license number
     */
    public void setNumber(String number) {
        data.put(Field.NUMBER, number);
    }

    /**
     *
     * @return the proof File
     */
    public Integer getFile() {
        return (Integer) data.get(Field.FILE);
    }

    /**
     *
     * @param file the proof File
     */
    public void setFile(Integer file) {
        data.put(Field.FILE, file);
    }

}
