package objects;

import java.util.EnumMap;

/**
 * A permission in the system. I.e. block users
 */
public class Permission extends DataObject {

    public enum Field implements DataField {

	ID(Integer.class, true, false),
	NAME(String.class);

	private final boolean stamp;
	private final boolean key;
	private final Class type;

	private Field(Class type, boolean key, boolean stamp) {
		this.type = type;
		this.key = key;
		this.stamp = stamp;
	}
	
	private Field(Class type) {
		this.type = type;
		this.key = false;
		this.stamp = false;
	}
	
	@Override
	public Class getType() {
		return type;
	}

	@Override
	public boolean isKey() {
		return key;
	}

	@Override
	public boolean isStamp() {
		return stamp;
	}

    }

    /**
     *
     * @param id the id generated by the db
     * @param name the name of the role
     */
    public Permission(Integer id, String name) {
        super(new EnumMap<>(Field.class));
        data.put(Field.ID, id);
        data.put(Field.NAME, name);
    }
    
    

    /**
     *
     * @return the id assigned by the db
     */
    public Integer getId() {
        return (Integer) data.get(Field.ID);
    }

    /**
     *
     * @return the name of the role
     */
    public String getName() {
        return (String) data.get(Field.NAME);
    }

    /**
     *
     * @param name the name of the role
     */
    public void setName(String name) {
        data.put(Field.NAME, name);
    }

}
